### PR TITLE
evan: add waiver screen

### PR DESCRIPTION
**Pull request by evanm510**
https://github.com/user-attachments/assets/efb28897-7429-4757-9352-7cb747751091

### CODE REVIEW

**Comment by campbeb3** [comment]
Very nice!

**Review by anisar17 — APPROVED** [review]
I like the video to show the changes in action!

**Review by anisar17 — CHANGES_REQUESTED** [review]
I think there might need to be some stuff changed in pubspec probably because I just merged Brian's PR. It looks like there's a line missing.

**Comment by campbeb3** [comment]
Fixed conflict

**Review by campbeb3 — APPROVED** [review]
Looks good, approved

**Review by kenneth-tucker — APPROVED** [review]

**Review by anisar17 — APPROVED** [review]
Thanks for making that change

**Pull request merged**
